### ISSUE TITLE
Look for help to make my gcloud safe

### ISSUE THREAD

**Issue by neftaperez** [smurfpandey/update-gcloud-firewall#2]
Well I been hack and they are abusing of knowing password for the reason I am look to make my network safe to use agin they are making thing difícil 
Thanks for all 
Email neftalipflores@gmail.com

**Comment by smurfpandey** [comment]
Use password manager like bitwarden https://bitwarden.com

https://www.troyhunt.com/only-secure-password-is-one-you-cant/
